# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ad275578eaea6399b8e201d77eb37f8a2c0e226ca82f5f0eb0715a2114b4ddba164679e404556c780c86e61cec2832bee7c13f729e3ea649f76ae23f59509bf

test:
  secret_key_base: 3ad90a7580ef6254a717244bb48f2ba30f8ffb97425f633ec2ce489c1f3ea03d4bd3f7fb1c216b8f00e8c02d3f4d76eb9ad9d8ed4dcf250d90ee4c54e062db52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
